# Generated by Django 4.1.7 on 2023-03-12 16:13

import django.core.files.storage
from django.db import migrations, models
import player.models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='audios'), upload_to=player.models.audio_upload_to),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=player.models.image_upload_to),
        ),
    ]
